[package]
name = "sndjvu"
version = "0.0.0"

edition = "2021"

[features]
std = ["sndjvu_format/std", "sndjvu_codec/std"]

[dependencies]
sndjvu_format = { version = "*", path = "../sndjvu_format" }
sndjvu_codec = { version = "*", path = "../sndjvu_codec", features = ["djvu"] }
