name: ci
on:
  push:
    branches:
      - master
jobs:
  go:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2022-08-11
      - uses: Swatinem/rust-cache@v2
      - run: ./x.sh ci
