name: www
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/www.yml'
      - 'x.sh'
      - 'www/**'
jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: ./x.sh www
